name: Publish Python 🐍 distributions 📦 to PyPI 

on: 
  release:
    types: [published]

permissions:
  contents: read

jobs:
  Lint:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      # clone the repo, run black and flake8 on it
      - uses: actions/checkout@v4
      - run: python -m pip install black==23.* flake8 isort
      - run: black --check .
      - run: isort --check .

  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: requirements_conda.yml
          python-version: 3.9
          auto-activate-base: false
      - name: Activate conda env
        shell: bash -l {0}
        run: |
          conda activate test
      - name: Install library for testing
        shell: bash -l {0}
        run: |
          pip install coveralls
          pip install .
      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest --pyargs chemplot
        
  Build-n-Publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    needs: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
