name: Tests

on: 
  - push
  - pull_request

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9']
        max-parallel: 5

    steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Add conda to system path
          run: |
            # $CONDA is an environment variable pointing to the root of the miniconda directory
            echo $CONDA/bin >> $GITHUB_PATH
        - name: Install conda dependencies
          run: |
            conda env update --file requirements_conda.yml --name base
        - name: Install pip dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements_dev.txt 
        - name: Test with pytest
          run: |
            pytest