name: Tests

on: 
  - push
  - pull_request

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy: 
      max-parallel: 4
      matrix:
        os: ["ubuntu-latest"]
        python-version: ['3.9']

    steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - uses: conda-incubator/setup-miniconda@v2
          with:
            auto-update-conda: true
            python-version: ${{ matrix.python-version }}
        - name: Activate conda env
          shell: bash -l {0}
          run: conda env create -f requirements_conda.yml

