name: Tests

on: 
  - push
  - pull_request

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy: 
      max-parallel: 4
      matrix:
        os: ["macos-latest"]
        python-version: ['3.9']

    steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Setup Miniconda
          uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: test
            environment-file: requirements_conda.yml
            python-version: ${{ matrix.python-version }}
            auto-activate-base: false
        - name: Activate conda env
          shell: bash -l {0}
          run: |
            conda activate test
